### ISSUE TITLE
[Feature 8]  Improve Entity Documentation And Testing

### ISSUE THREAD

**Issue by katarinaavucic** [CSC207-2023Y-UofT/course-project-DoorKeepers#10]
Write better Javadocs and more tests for the entities that cover edge cases

**Comment by aricasas** [comment]
Here's a description for SessionStorage we can use for its JavaDoc
A class that will store all the user data for a session. This includes a list of MonthlyStorage objects to store the data for several months, and a list of recurring expenses that apply to every month.
